---
version: 1.0.0
slug: vlc
name: VLC Custom Player
description: Turn your device into a Media Player with VLC and custom alarm clock
url: https://github.com/lijiazhiren/addons/tree/master/vlc
arch:
  - amd64
  - i386
  - armv7
  - aarch64
audio: true
discovery:
  - vlc_telnet
homeassistant: 2024.1.0
ingress: true
init: false
map:
  - share:ro
  - media:ro
ports:
  8080/tcp: null
  8080/udp: null
options: {}
panel_icon: mdi:vlc
schema: false
stage: stable
startup: services
