{
  "name": "Workday Alarm Clock",
  "version": "1.0.0",
  "slug": "workdayalarmclock",
  "description": "An alarm clock Add-on that uses host audio and exposes a network port.",
  "arch": ["aarch64", "amd64", "armhf", "armv7"],
  "startup": "application",
  "stage": "stable",
  "ports": {
    "8080/tcp": 8080,
    "8080/udp": 8080
  },
  "ports_description": {
    "8080/tcp": "Internal application TCP port for alarm control",
    "8080/udp": "Internal application UDP port"
  },
  "options": {},
  "schema": {},
  "host_audio": true,
  "devices": ["/dev/snd"],
  "boot": "auto"
}
