# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: qqExample
version: "1.2.1"
slug: wwexample
description: rrExample add-on
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
audio: true
init: false
map:
  - share:rw
options:
  message: "Hello world..."
ports:
  8080/tcp: 8080
  8080/udp: 8080
schema:
  message: "str?"
#image: "ghcr.io/home-assistant/{arch}-addon-example"
